### ISSUE TITLE
Crash on android less than 5.0

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#53]
Hi there!
I'm trying to get it working on android 4.0.4 and have troubles with unimplemented 'rand', 'srand' and some other functions.
The problem looks similar to this:
https://stackoverflow.com/questions/27338318/cannot-load-library-reloc-library1285-cannot-locate-rand
It works fine on devices with api >= 21 and crashes on older ones.

When I change platformVersion to 19 in build.gradle, I get an error: undefined reference to 'rand'..
Is it possible to use SvgRen on android with api less than 21?

Thanks in advance for any ideas and thoughts )

**Comment by igagis** [comment]
How do you use it with android? Do you install it as described in the wiki [here](https://github.com/igagis/svgren/blob/master/wiki/InstallAndroid.adoc)? Or do you compile it from sources yourself?
In that stackoverflow topic there is an answer which suggests some kind of solution https://stackoverflow.com/a/38499898/1221106 have you tried it?
What is the exact list of functions which are unimplemented in your case?
It seems like there are some differences in standard library between api 20 and 21...

**Comment by Papirosnik** [comment]
I build shared library with your slightly modified build.gradle.

These functions are defined in stdlib.h and cannot be located at compile time when I set platformVersion option to 19 and at runtime when it's set to 21.
 
static  __inline__ int rand(void) {
    return (int)lrand48();
}
static  __inline__ void srand(unsigned int __s) {
    srand48(__s);
}
static  __inline__ long random(void)
{
    return lrand48();
}

static  __inline__ void srandom(unsigned int __s)
{
    srand48(__s);
}

**Comment by igagis** [comment]
Can you try defining those functions yourself as described in https://stackoverflow.com/a/38499898/1221106 ? It might be the solution, but I think would be nice to have some kind of `#ifdef` to do it on when building for api 19

**Comment by Papirosnik** [comment]
I will try right now

**Comment by Papirosnik** [comment]
some related info
https://issuetracker.google.com/issues/37000040
They state that that is Intended Behavior and Won't Fix (

**Comment by igagis** [comment]
I assume Android 4 devices are still quite common and it is undesirable to drop their support?

**Comment by Papirosnik** [comment]
Yes, they are still pretty popular

**Comment by Papirosnik** [comment]
I managed to get it working on Android 4.0.4 device by manually adding above mentioned functions to my sources

**Comment by igagis** [comment]
Good that you got it working, but does it compile on api 21 now with those functions added?

**Comment by Papirosnik** [comment]
Yes, it can be compiled on api 21 with both static and shared stdlib and works perfectly on devices targeting API >= 21 but on the older devices it works only with statically linked stdlib.

**Comment by igagis** [comment]
Ok, good to know! Maybe this solution helps somebody else. Thanks!
